project_id = "eydjkasswyygiycitnml"

[functions.collect-momo]
verify_jwt = false

[functions.checkout-session]
verify_jwt = false

[functions.transaction-status]
verify_jwt = false

[functions.list-transactions]
verify_jwt = false

[functions.liberte-callback]
verify_jwt = false

[functions.junipay-callback]
verify_jwt = false


[functions.send-email]
verify_jwt = false

[functions.team-invites]
verify_jwt = true

[functions.business-transfer]
verify_jwt = true

[functions.admin-verification-reminder]
verify_jwt = false

[functions.messaging-send]
verify_jwt = true

[functions.messaging-status]
verify_jwt = true

[functions.messaging-sender-id]
verify_jwt = true

[functions.messaging-voice]
verify_jwt = true

[functions.messaging-otp]
verify_jwt = true

[functions.messaging-balance]
verify_jwt = true

[functions.admin-messaging]
verify_jwt = true

[functions.messaging-topup]
verify_jwt = true

[functions.messaging-topup-status]
verify_jwt = true

[functions.messaging-cancel]
verify_jwt = true
