project_id = "eydjkasswyygiycitnml"

[functions.collect-momo]
verify_jwt = false

[functions.checkout-session]
verify_jwt = false

[functions.transaction-status]
verify_jwt = false

[functions.list-transactions]
verify_jwt = false

[functions.liberte-callback]
verify_jwt = false

[functions.junipay-callback]
verify_jwt = false


[functions.send-email]
verify_jwt = false

[functions.team-invites]
verify_jwt = true

[functions.admin-verification-reminder]
verify_jwt = false
