project_id = "eydjkasswyygiycitnml"

[functions.collect-momo]
verify_jwt = false

[functions.collect-card]
verify_jwt = false

[functions.payout-momo]
verify_jwt = false

[functions.transaction-status]
verify_jwt = false

[functions.list-transactions]
verify_jwt = false

[functions.send-email]
verify_jwt = false
