// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eydjkasswyygiycitnml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5ZGprYXNzd3l5Z2l5Y2l0bm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUxOTM0ODYsImV4cCI6MjEwMDc2OTQ4Nn0.Y7IKnmjSUeWMXs5PabDNSd2YeciPFmpmhokiJBbOnSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});